#!/usr/bin/env bash
LC_ALL=C

local_branch="$(git rev-parse --abbrev-ref HEAD)"
echo "Branch Name = $local_branch"

valid_branch_regex="^(development|homolog|main|master|((release|feature|bugfix|hotfix)\/[a-z0-9-]+)|(patch\/[0-9]+\.[0-9]+\.x))$"
message="There is something wrong with your branch name. Branch names in this project must adhere to this contract: $valid_branch_regex. Your push will be rejected. You should rename your branch to a valid name and try again."

if [[ ! $local_branch =~ $valid_branch_regex ]]
then
    echo "$message"
    exit 1
fi

exit 0
